services:
  - type: web
    name: salon-amanda
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py importar_productos
    startCommand: gunicorn config.wsgi:application --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
