# Generated by Django 6.0.5 on 2026-06-06 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('precio', models.PositiveIntegerField(default=0, help_text='Precio referencial en CLP')),
                ('precio_regular', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_oferta', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion_corta', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_principal', models.CharField(blank=True, help_text='Ruta relativa en static, ej: img/productos/slug-1.jpg', max_length=255)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(help_text='Ruta relativa en static', max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['orden'],
            },
        ),
    ]
