# Generated by Django 6.0.5 on 2026-07-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('btn_texto', models.CharField(default='Reservar ahora', max_length=60)),
                ('btn_url', models.CharField(default='https://link.agendapro.com/cl/salonamanda/9581b2de', max_length=500)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar vacío = sin vencimiento', null=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
    ]
