# Generated by Django 6.0.5 on 2026-07-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto de la promo (jpg/png). Opcional.', null=True, upload_to='promociones/'),
        ),
    ]
